UI: Footer Done
proceduretech/website pull request #19
Opened 2022-01-18 06:04 UTC by rizwan2000rm

Footer done

2022-01-18 06:11 UTC, ulhas requested changes

2022-01-18 06:11 UTC, ulhas commented on src/components/Footer/footer.tsx
> +  return (
We can remove this return statement

2022-01-18 06:11 UTC, ulhas commented on src/pages/index.tsx
> +import Footer from '../components/Footer/footer'
Can we make a barrel import file and import it from there?

2022-01-18 06:11 UTC, ulhas commented on src/components/Footer/footer.tsx
> +          <div className="cursor-pointer hover:opacity-80">Link1</div>
Can this be extracted to a component?

2022-01-18 06:11 UTC, ulhas commented on src/components/Footer/footer.tsx
> +          <div className="bg-white w-6 h-6 rounded-full"></div>
This as well. Helps with readability

2022-01-19 12:53 UTC, raveracker commented
I am closing this as I have made the changes and pushed it in another branch, will raise a new PR for that

2022-01-19 12:53 UTC, closed without merging