UI: Footer Changes and Develop Merge
proceduretech/website pull request #22
Opened 2022-01-19 12:54 UTC by raveracker

2022-01-19 14:38 UTC, ulhas requested changes

2022-01-19 14:38 UTC, ulhas commented on src/components/footer-menu.tsx
> +  <div className="flex gap-8 md:gap-12 justify-center items-center mt-10">
remove the implicit `mt-10` from the component. it should be passed as `className` prop or added to a wrapping div.

2022-01-19 15:46 UTC, raveracker commented on src/components/footer-menu.tsx
> +  <div className="flex gap-8 md:gap-12 justify-center items-center mt-10">
Done, I did not notice that earlier

2022-01-19 16:10 UTC, ulhas requested changes

2022-01-19 16:10 UTC, ulhas commented on src/containers/footer.tsx
> +          className="flex gap-8 md:gap-12 justify-center items-center mt-10"
check slack comment

2022-01-24 06:34 UTC, pallavisaraogi commented on src/containers/footer.tsx
> +const socialLinks = [
move this to `src/shared/sample-data.ts`

2022-01-24 07:12 UTC, raveracker commented on src/containers/footer.tsx
> +const socialLinks = [
These are jsx components, cannot be moved in a .ts file, also there would be changes on the data side that needs to be done after all the sections are done. The data part would be entirely done in graphql

2022-01-24 07:27 UTC, pallavisaraogi approved these changes

2022-01-24 07:50 UTC, merged