Feat/testimonial
proceduretech/website pull request #30
Opened 2022-01-27 16:53 UTC by SaistaShaikh

2022-02-02 06:23 UTC, ulhas requested changes

2022-02-02 06:23 UTC, ulhas commented on src/assets/images/dot.svg
> +<ellipse cx="10.1383" cy="10" rx="9.41352" ry="10" fill="#9E7BFE"/>
Indentation is off here.

2022-02-02 06:23 UTC, ulhas commented on src/components/avatar.tsx
> +        <img
We can separate this into small components and use it here

2022-02-03 03:46 UTC, pallavisaraogi commented on src/components/avatar.tsx
> +        <div
make this as a component and same can be use for active state by passing active classes

2022-02-03 03:46 UTC, pallavisaraogi commented on src/components/testimonial.tsx
> +    array[activeIndex] = temp
here activeIndex can be set directly by `setActiveIndex`. why swapping?

2022-02-03 03:46 UTC, pallavisaraogi commented on src/components/testimonial.tsx
> +        <div className=" mx-4 py-4 sm:w-3/4 shadow-xl rounded-2xl relative">
break this into components for showing active testimonial details

2022-02-09 16:52 UTC, closed without merging